const counties = [
  "Alameda County",
  "Amador County",
  "Butte County",
  "Calaveras County",
  "Contra Costa County",
  "Del Norte County",
  "El Dorado County",
  "Fresno County",
  "Humboldt County",
  "Imperial County",
  "Inyo County",
  "Kern County",
  "Kings County",
  "Lake County",
  "Lassen County",
  "Los Angeles County",
  "Madera County",
  "Marin County",
  "Mendocino County",
  "Merced County",
  "Monterey County",
  "Napa County",
  "Nevada County",
  "Orange County",
  "Placer County",
  "Plumas County",
  "Riverside County",
  "Sacramento County",
  "San Benito County",
  "San Bernardino County",
  "San Diego County",
  "San Francisco County",
  "San Joaquin County",
  "San Luis Obispo County",
  "San Mateo County",
  "Santa Barbara County",
  "Santa Clara County",
  "Santa Cruz County",
  "Shasta County",
  "Siskiyou County",
  "Solano County",
  "Sonoma County",
  "Stanislaus County",
  "Sutter County",
  "Tehama County",
  "Tulare County",
  "Tuolumne County",
  "Ventura County",
  "Yolo County",
  "Yuba County"
]
const industries = [
  "Goods Producing",
  "Other Services",
  "Arts, Entertainment, and Recreation",
  "Administrative and Support and Waste Ser",
  "Retail Trade",
  "Nondurable Goods",
  "Educational and Health Services",
  "Leisure and Hospitality",
  "Health Care and Social Assistance",
  "Information",
  "Natural Resources, Mining and Constructi",
  "Total Farm",
  "Local Government",
  "Federal Government",
  "Financial Activities",
  "Service Providing",
  "Trade, Transportation and Utilities",
  "Government",
  "Accommodation and Food Service",
  "Total Wage and Salary",
  "Durable Goods",
  "Professional, Scientific and Technical S",
  "Educational Services",
  "Professional and Business Services",
  "Real Estate and Rental and Leasing",
  "Total Nonfarm",
  "Transportation, Warehousing and Utilitie",
  "Wholesale Trade",
  "State Government",
  "Finance and Insurance",
  "Management of Companies and Enterprises",
  "Manufacturing"
]

export { counties, industries }