const counties = [
  "Alameda County",
  "Amador County",
  "Butte County",
  "Calaveras County",
  "Contra Costa County",
  "Del Norte County",
  "El Dorado County",
  "Fresno County",
  "Humboldt County",
  "Imperial County",
  "Inyo County",
  "Kern County",
  "Kings County",
  "Lake County",
  "Lassen County",
  "Los Angeles County",
  "Madera County",
  "Marin County",
  "Mendocino County",
  "Merced County",
  "Monterey County",
  "Napa County",
  "Nevada County",
  "Orange County",
  "Placer County",
  "Plumas County",
  "Riverside County",
  "Sacramento County",
  "San Benito County",
  "San Bernardino County",
  "San Diego County",
  "San Francisco County",
  "San Joaquin County",
  "San Luis Obispo County",
  "San Mateo County",
  "Santa Barbara County",
  "Santa Clara County",
  "Santa Cruz County",
  "Shasta County",
  "Siskiyou County",
  "Solano County",
  "Sonoma County",
  "Stanislaus County",
  "Sutter County",
  "Tehama County",
  "Tulare County",
  "Tuolumne County",
  "Ventura County",
  "Yolo County",
  "Yuba County"
]
const industries = [
  "Accommodation and Food Service", 
  "Administrative and Support and Waste Ser", 
  "Arts, Entertainment, and Recreation", 
  "Durable Goods", 
  "Educational Services", 
  "Educational and Health Services", 
  "Federal Government", 
  "Finance and Insurance", 
  "Financial Activities", 
  "Goods Producing", 
  "Government", 
  "Health Care and Social Assistance", 
  "Information", 
  "Leisure and Hospitality", 
  "Local Government", 
  "Management of Companies and Enterprises", 
  "Manufacturing", 
  "Natural Resources, Mining and Constructi", 
  "Nondurable Goods", 
  "Other Services", 
  "Professional and Business Services", 
  "Professional, Scientific and Technical S", 
  "Real Estate and Rental and Leasing", 
  "Retail Trade", 
  "Service Providing", 
  "State Government", 
  "Total Farm", 
  "Total Nonfarm", 
  "Total Wage and Salary", 
  "Trade, Transportation and Utilities", 
  "Transportation, Warehousing and Utilitie", 
  "Wholesale Trade"
]

const years = [
  1990,
  1991,
  1992,
  1993,
  1994,
  1995,
  1996,
  1997,
  1998,
  1999,
  2000,
  2001,
  2002,
  2003,
  2004,
  2005,
  2006,
  2007,
  2008,
  2009,
  2010,
  2011,
  2012,
  2013,
  2014,
  2015,
  2016,
  2017
]

export { counties, industries, years }